### ISSUE TITLE
CLI-To-Whatsapp reused in Whatsapp-Notif

### ISSUE THREAD

**Issue by mohamed-rouissi** [cankush625/CLI-To-Whatsapp#1]
Hello @cankush625,

Hope you're doing well. 

It was just to inform you that I reused the idea of your script (CLI-To-Whatsapp) in order to adapt it to my requirements. 

Here is the link: https://github.com/aftermath8/Whatsapp-Notif

Thank you very much and don't hesitate to contact me if you have any questions.

**Comment by cankush625** [comment]
No problem! Glad to hear that it helped you to achieve your requirements. 😊
